# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

这是 numpy 邮件列表、stack overflow 和 numpy 文档中收集的练习。本练习集的目的是为新老用户提供快速参考，同时也为教学人员提供一套练习。
和新用户提供快速参考，同时也为教学人员提供一套练习。

If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
# hint(2)

print(np.__version__)
np.show_config()

2.2.3
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
     

/Users/minghuang/miniconda3/envs/np100/lib/python3.12/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [12]:
hint(4)
answer(4)

hint: size, itemsize
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


In [13]:
Z = np.zeros((10, 10))

In [14]:
Z.size

100

In [15]:
Z.itemsize

8

In [17]:
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
hint(5)

hint: np.info


In [19]:
np.info(Z)

class:  ndarray
shape:  (10, 10)
strides:  (80, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x102f2a440
byteorder:  little
byteswap:  False
type: float64


In [20]:
answer(5)

%run `python -c "import numpy; numpy.info(numpy.add)"`


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [22]:
hint(6)

hint: array[4]


In [25]:
answer(6)

Z = np.zeros(10)
Z[4] = 1
print(Z)


In [26]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [27]:
hint(7)

hint: arange


In [29]:
answer(7)

Z = np.arange(10,50)
print(Z)


In [30]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [31]:
hint(8)

hint: array[::-1]


In [32]:
reversed_Z = Z[::-1]

In [33]:
print(reversed_Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [34]:
answer(8)

Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [36]:
Z = np.arange(9)
Z = Z.reshape((3, 3))
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
answer(9)

Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [38]:
hint(10)

hint: np.nonzero


In [39]:
original = np.array([1, 2, 0, 0, 4, 0])
original.nonzero()

(array([0, 1, 4]),)

In [40]:
answer(10)

nz = np.nonzero([1,2,0,0,4,0])
print(nz)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [41]:
hint(11)

hint: np.eye


In [44]:
identity_3 = np.eye(3, 3)
print(identity_3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [49]:
hint(12)

hint: np.random.random


In [51]:
rand_3_3_3 = np.random.random((3, 3, 3))

In [52]:
print(rand_3_3_3)

[[[0.48065538 0.92873315 0.10509562]
  [0.33890031 0.90305596 0.30214985]
  [0.94716112 0.26430499 0.98914185]]

 [[0.62534273 0.80714224 0.45239946]
  [0.92274038 0.82683482 0.97441494]
  [0.55644099 0.32608594 0.03814744]]

 [[0.70898376 0.85338688 0.8866924 ]
  [0.69624163 0.25272142 0.21160847]
  [0.59974054 0.00603929 0.64172003]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [55]:
hint(13)

hint: min, max


In [54]:
rand_10_10 = np.random.random((10, 10))
print(rand_10_10)

[[0.96124412 0.12014061 0.47863871 0.92272207 0.5222659  0.0165563
  0.76287384 0.61768775 0.11436058 0.69339566]
 [0.54069769 0.28776913 0.60025134 0.89610847 0.09799706 0.74397191
  0.16467497 0.71118737 0.15076941 0.28768018]
 [0.26991224 0.85553921 0.52847426 0.68394833 0.89910625 0.47551266
  0.03154272 0.22744449 0.89508776 0.02106596]
 [0.66561793 0.32716587 0.09908533 0.1500192  0.87250857 0.92751396
  0.96356957 0.92613186 0.52842259 0.87682681]
 [0.45072817 0.04964105 0.06212746 0.77621698 0.05610299 0.95155648
  0.24059791 0.1345742  0.93177096 0.76495492]
 [0.31014824 0.34389186 0.61077331 0.97766239 0.35281225 0.216134
  0.18667771 0.0413533  0.34826857 0.77696023]
 [0.94488901 0.78692342 0.41113286 0.56889182 0.42038    0.15398543
  0.49432376 0.60050908 0.6965374  0.49030321]
 [0.30544808 0.26577776 0.37056464 0.5721474  0.99720046 0.20869541
  0.6183266  0.60917374 0.09424579 0.44857318]
 [0.8445811  0.52229305 0.15337018 0.01717215 0.12705106 0.02905176
  0.93109759 0.

In [58]:
rand_10_10.min()

np.float64(0.016556298243849854)

In [59]:
rand_10_10.max()

np.float64(0.9972004592162228)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [60]:
vec_30 = np.random.random(30)

In [61]:
print(vec_30)

[0.81075764 0.91791831 0.99199078 0.84026758 0.47793128 0.31432665
 0.6252318  0.28974152 0.3766213  0.72102977 0.16022595 0.8133259
 0.01555154 0.26740544 0.84863664 0.94319324 0.41196615 0.66009409
 0.93316861 0.73340034 0.77331215 0.41650136 0.60615752 0.09651958
 0.48162415 0.36061559 0.67691955 0.96992151 0.02100163 0.8302314 ]


In [63]:
vec_30.mean()

np.float64(0.5795196322960584)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) (10, 10)

In [ ]:
hint(15)

hint: array[1:-1, 1:-1]


In [68]:
Z = np.ones((10, 10))
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [69]:
Z[1:-1, 1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [70]:
Z = np.random.random((4, 4))
print(Z)

[[0.3081469  0.21465225 0.12333254 0.89258711]
 [0.24306384 0.85936297 0.17194861 0.81220301]
 [0.22522982 0.66894941 0.58331198 0.51431538]
 [0.97170764 0.56025854 0.99835719 0.4908817 ]]


In [72]:
padded_Z = np.pad(array=Z, pad_width=1, mode="constant", constant_values=0)
print(padded_Z)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.3081469  0.21465225 0.12333254 0.89258711 0.        ]
 [0.         0.24306384 0.85936297 0.17194861 0.81220301 0.        ]
 [0.         0.22522982 0.66894941 0.58331198 0.51431538 0.        ]
 [0.         0.97170764 0.56025854 0.99835719 0.4908817  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [73]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


In [ ]:
## Fancy way?
Z = np.ones((5,5))
padded_Z_2 = Z.copy()
padded_Z_2[[0, -1], [0, -1]] = 0
print(padded_Z_2)

[[0.         0.21465225 0.12333254 0.89258711]
 [0.24306384 0.85936297 0.17194861 0.81220301]
 [0.22522982 0.66894941 0.58331198 0.51431538]
 [0.97170764 0.56025854 0.99835719 0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [77]:
0 * np.nan

nan

In [78]:
np.nan == np.nan

False

因为`np.nan`（Not a Number）表示一个未定义或不可表示的值，它不与任何值相等，包括它自己。需要使用`isnan`判断

In [81]:
1 if np.isnan(np.nan) else 0

1

In [82]:
1 if np.isnan(3) else 0

0

In [83]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan # 对np.nan的任何运算都是nan

nan

In [85]:
np.nan in set([np.nan])

True

In [91]:
print(hash(np.nan))  # 输出一个固定的整数值
print(hash(float('nan')))

273990251
283835451


In [89]:
print(np.nan is np.nan)  # 输出: True

True


In [ ]:
s = set([np.nan, float('nan'), np.nan])
print(s)  # np.nan和float('nan')是不一样的

{nan, nan}


In [86]:
0.3 == 3 * 0.1

False

In [92]:
print(np.isclose(0.3, 3 * 0.1))

True


In [93]:
hint(17)

hint: NaN = not a number, inf = infinity


In [94]:
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [98]:
Z_55 = np.zeros((5, 5))
print(Z_55)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [100]:
hint(18)
answer(18)

hint: np.diag
Z = np.diag(1+np.arange(4),k=-1)
print(Z)


In [106]:
Z_55 = np.diag(np.arange(1,5,1), k=-1)
print(Z_55)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [107]:
hint(19)

hint: array[::2]


In [108]:
answer(19)

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


In [110]:
Z = np.zeros((8,8),dtype=int)
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [111]:
Z[1::2,::2]=1
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [112]:
Z[::2, 1::2]=1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
# 99 / (7 * 8) = 1, so x = 1
# 99 - 7 * 8 = 43
# 43 / 8 = 5, so y = 5
# 43 % 7 = 3, so z = 3
# (x,y,z) = (1, 5, 3)

In [113]:
Z = np.arange(6*7*8).reshape((6,7,8))
print(Z)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [114]:
hint(20)

hint: np.unravel_index


In [115]:
answer(20)

print(np.unravel_index(99,(6,7,8)))


In [116]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


In [ ]:
np.unravel_index(indices=99, shape=(6,7,8))

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
Z_88 = np.tile(A=np.array([0, 1]), reps=32).reshape(8,8)
print(Z_88)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [127]:
answer(21)

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


In [128]:
Z = np.tile(
    A=np.array([[0, 1], [1, 0]]),
    reps=(4, 4)
)
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
norm_55 = np.random.random((5, 5))
print(norm_55)

[[0.90471458 0.92155631 0.98084827 0.96553085 0.34267228]
 [0.94158553 0.89292143 0.85945381 0.65035927 0.61592921]
 [0.72588087 0.03198806 0.20313792 0.29433516 0.4784765 ]
 [0.81818691 0.90646826 0.79086775 0.76509062 0.28643035]
 [0.36064273 0.65619875 0.70247592 0.84253439 0.05249911]]


In [133]:
normalized_55 = (norm_55 - norm_55.mean()) / norm_55.std()
print(normalized_55)

[[ 0.91208614  0.97003442  1.17404349  1.12133999 -1.02176338]
 [ 1.03895002  0.87150881  0.75635497  0.03691199 -0.08155338]
 [ 0.29676328 -2.09075152 -1.50186686 -1.18807956 -0.5544944 ]
 [ 0.61436568  0.91812014  0.52036715  0.43167441 -1.21527807]
 [-0.95993148  0.05700422  0.2162326   0.69813939 -2.02017803]]


In [134]:
hint(22)
answer(22)

hint: (x -mean)/std
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
hint(23)
answer(23)

hint: np.dtype
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


In [ ]:
color = np.dtype([
    ("r", np.ubyte),
    ("g", np.ubyte),
    ("b", np.ubyte),
    ("a", np.ubyte),
])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [138]:
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color)
print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


In [139]:
print(colors["r"]) # 访问所有元素的红色通道

[255   0   0]


In [140]:
# 访问第一个元素的绿色通道
print(colors[0]["g"])  # 输出: 0

0


In [141]:
# 修改第二个元素的蓝色通道
colors[1]["b"] = 128
print(colors)

[(255,   0,   0, 255) (  0, 255, 128, 255) (  0,   0, 255, 255)]


In [142]:
for c in colors: # 遍历数组中的每个元素，并访问其字段。
    print(f"r={c['r']}, g={c['g']}, b={c['b']}, a={c['a']}")

r=255, g=0, b=0, a=255
r=0, g=255, b=128, a=255
r=0, g=0, b=255, a=255


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [143]:
left = np.random.random((5, 3))
right = np.random.random((3, 2))
print(left)
print(right)

[[0.95666299 0.28052165 0.13375034]
 [0.40760117 0.50044555 0.53553015]
 [0.56329291 0.14353592 0.81466499]
 [0.43887777 0.69182837 0.74457992]
 [0.05296208 0.13597438 0.28836897]]
[[0.08596036 0.9454194 ]
 [0.55378837 0.31563088]
 [0.53072439 0.46702229]]


In [147]:
print(left @ right)

[[0.30856929 1.05545343]
 [0.59639738 0.79341464]
 [0.56027196 0.95831912]
 [0.81601932 0.98102138]
 [0.23289811 0.22766382]]


In [146]:
hint(24)
answer(24)

hint:
Z = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
#### 25. 给定一个一维数组，将所有介于 3 和 8 之间的元素就地变负。(★☆☆)

In [150]:
Z = np.arange(11)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [152]:
Z[(Z > 3) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [153]:
answer(25)

# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

`range(5)`给出的是(0,1,2,3,4)，sum的第一个参数就是这个，第二个参数是-1。

`sum`函数的第二个参数是和的起始值，那么答案就是sum(range(5)) + (-1) = 10 + (-1) = 9


In [157]:
for i in range(5):
    print(i)

0
1
2
3
4


In [154]:
print(sum(range(5),-1))

9


In [159]:
answer(26)

# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [163]:
answer(27)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


In [ ]:
Z= np.array([3, 4, 5])

In [161]:
Z ** Z

array([  27,  256, 3125])

In [166]:
2 << Z

array([16, 32, 64])

In [165]:
(2 << Z) >> 2

array([ 4,  8, 16])

In [167]:
Z <- Z

array([False, False, False])

In [168]:
1j*Z

array([0.+3.j, 0.+4.j, 0.+5.j])

In [169]:
Z/1/1

array([3., 4., 5.])

In [170]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [171]:
np.array(0) / np.array(0)

/var/folders/32/h68qwycj5j770f873m9dns9m0000gn/T/ipykernel_31729/873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [172]:
np.array(0) // np.array(0)

/var/folders/32/h68qwycj5j770f873m9dns9m0000gn/T/ipykernel_31729/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [173]:
np.array([np.nan]).astype(int).astype(float)

/var/folders/32/h68qwycj5j770f873m9dns9m0000gn/T/ipykernel_31729/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([0.])

#### 29. How to round away from zero a float array ? (★☆☆)

In [174]:
hint(29)

hint: np.uniform, np.copysign, np.ceil, np.abs, np.where


#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)